pool:
  vmImage: 'macos-latest'
steps:
  - script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 5_12_0
    displayName: 'Select the Xamarin SDK version'
    enabled: false
  - task: MSBuild@1
    displayName: Build Android samples
    inputs:
      solution: '**/*Droid*.csproj'
      configuration: 'Debug'
      msbuildArguments: '/restore /t:Build /p:ContinuousIntegrationBuild=true /p:Deterministic=false'    